import numpy as np


class DynamicStateMultipleTrueValues1D(object):
	INITIAL_ESTIMATE_POSITION = 4000
	INITIAL_ESTIMATE_VELOCITY = 280

	INITIAL_ACCELERATION = 2

	TIME_DIFF = 1

	ESTIMATE_ERROR_POSITION = 20
	ESTIMATE_ERROR_VELOCITY = 5

	OBSERVATION_ERROR_POSITION = 25
	OBSERVATION_ERROR_VELOCITY = 6

	# matrix A
	STATE_MULTIPLIER_MATRIX = np.array([[1, TIME_DIFF], [0, 1]])

	# matrix B
	CONTROL_VARIABLE_MULTIPLIER_MATRIX = np.array([[0.5*TIME_DIFF*TIME_DIFF], [TIME_DIFF]])

	CONTROL_VARIABLE_MATRIX = np.array([[INITIAL_ACCELERATION]])

	# process errors (in model)
	STATE_PREDICTION_PROCESS_ERROR_MATRIX = np.array([[0.0], [0.0]])
	PREDICTED_ESTIMATE_PROCESS_ERROR_MATRIX = np.array([[0.0, 0.0], [0.0, 0.0]])
	NEW_OBSERVATION_PROCESS_ERROR_MATRIX = np.array([[0.0], [0.0]])

	MEASUREMENT_DATA_FILE = 'resources/example_dynamic_state_1d'